export const classesData = [
  // text
  // teal-100
  // slate-900
  {
    name: "Warrior",
    icon: "",
    color: "bg-warrior",
    text: "text-slate-900",
    key: 1,
  },
  {
    name: "Warlock",
    icon: "",
    color: "bg-warlock",
    text: "text-slate-900",
    key: 2,
  },
  {
    name: "Monk",
    icon: "",
    color: "bg-monk",
    text: "text-slate-900",
    key: 3,
  },
  {
    name: "Shaman",
    icon: "",
    color: "bg-shaman",
    text: "text-white",
    key: 4,
  },
  {
    name: "Rogue",
    icon: "",
    color: "bg-rogue",
    text: "text-slate-900",
    key: 5,
  },
  {
    name: "Priest",
    icon: "",
    color: "bg-priest",
    text: "text-slate-900",
    key: 6,
  },
  {
    name: "Demon Hunter",
    icon: "",
    color: "bg-dh",
    text: "text-white",
    key: 7,
  },
  {
    name: "Druid",
    icon: "",
    color: "bg-druid",
    text: "text-slate-900",
    key: 8,
  },
  {
    name: "Hunter",
    icon: "",
    color: "bg-hunter",
    text: "text-slate-900",
    key: 9,
  },
  {
    name: "Mage",
    icon: "",
    color: "bg-mage",
    text: "text-slate-900",
    key: 10,
  },
  {
    name: "Death Knight",
    icon: "",
    color: "bg-dk",
    text: "text-white",
    key: 11,
  },
  {
    name: "Paladin",
    icon: "",
    color: "bg-paladin",
    text: "text-slate-900",
    key: 12,
  },
  {
    name: "Evoker",
    icon: "",
    color: "bg-evoker",
    text: "text-slate-900",
    key: 13,
  },
];
